context {
  features {
    key: "label"
    value {
      description: "compound entropy"
      dtype: DT_FLOAT
    }
  }
}
node_sets {
  key: "atoms"
  value {
    features {
      key: "hidden_state"
      value {
        description: "atomic_number representing atom type"
        dtype: DT_FLOAT
        shape {
          dim {
            size: 3
          }
        }
      }
    }
  }
}
edge_sets {
  key: "bonds"
  value {
    features {
      key: "hidden_state"
      value {
        description: "bond type."
        dtype: DT_FLOAT
        shape {
          dim {
            size: 4
          }
        }
      }
    }
    source: "atoms"
    target: "atoms"
  }
}
